### ISSUE TITLE
Add support for jsconfig paths by bumping tsconfig-paths to 4.0 

### ISSUE THREAD

**Issue by alexeyds** [egoist/esbuild-register#85]
`tsconfig-paths` did not have support for jsconfig.json files until 4.0(https://github.com/dividab/tsconfig-paths/pull/199) and `esbuild-register` is using version 3.12 at the moment. Would be nice to have it bumped if possible

Also, if anyone is looking for a temporary solution, installing `tsconfig-paths` yourself and adding this before registering esbuild hooks worked for me:

```
const tsConfigPaths = require("tsconfig-paths");
tsConfigPaths.register();
```

**Comment by Karibash** [comment]
Starting with TypeScript 5.0, it is now possible to [specify arrays in extends](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#supporting-multiple-configuration-files-in-extends).
Since an error occurs when specifying arrays in extends in tsconfig-paths version 3.1.2, it is necessary to upgrade to [version 4.2.0](https://github.com/dividab/tsconfig-paths/blob/master/CHANGELOG.md#420---2023-03-29)
